<Project Sdk="Microsoft.NET.Sdk.BlazorWebAssembly">
    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <Nullable>disable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <RootNamespace>Cloud5mins.ShortenerTools.TinyBlazorAdmin</RootNamespace>
        <DebugType>portable</DebugType>
        <PublishTrimmed>false</PublishTrimmed>
    </PropertyGroup>
    <ItemGroup>
        <PackageReference Include="MudBlazor" Version="8.15.0"/>
        <PackageReference Include="Microsoft.AspNetCore.App.Internal.Assets" Version="10.0.11"/>
        <PackageReference Include="Microsoft.NET.ILLink.Tasks" Version="10.0.11"/>
        <PackageReference Include="Microsoft.NET.Sdk.WebAssembly.Pack" Version="10.0.11"/>
        <PackageReference Include="Newtonsoft.Json" Version="13.0.4"/>
        <PackageReference Include="AnthonyChu.AzureStaticWebApps.Blazor.Authentication" Version="0.0.2-preview"/>
        <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly" Version="10.0.11"/>
        <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly.DevServer" Version="10.0.11"/>
        <PackageReference Include="Microsoft.Authentication.WebAssembly.Msal" Version="10.0.11"/>
        <PackageReference Include="System.Private.Uri" Version="4.3.2"/>
        <PackageReference Include="System.Text.Json" Version="10.0.11"/>
    </ItemGroup>
    <ItemGroup>
        <ProjectReference Include="..\Cloud5mins.ShortenerTools.Core\Cloud5mins.ShortenerTools.Core.csproj"/>
    </ItemGroup>
</Project>