<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<CarpaNet_JsonContextName>ATProtoJsonContext</CarpaNet_JsonContextName>
		<CarpaNet_LexiconAutoResolve>true</CarpaNet_LexiconAutoResolve>
	</PropertyGroup>
	<ItemGroup>
		<PackageReference Include="Azure.Communication.Email" Version="1.1.0" />
		<PackageReference Include="cronos" Version="0.13.0" />
		<PackageReference Include="Azure.Data.Tables" Version="12.12.0" />
		<PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="10.0.11" />
		<PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
		<PackageReference Include="System.Text.Json" Version="10.0.11" />
		<PackageReference Include="UAParser" Version="3.1.47" />

		<PackageReference Include="CarpaNet" Version="1.0.3" />
		<PackageReference Include="CarpaNet.SourceGen" Version="0.1.0-alpha.54">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
	</ItemGroup>

	<ItemGroup>
		<LexiconResolve Include="app.bsky.feed.post" />
		<LexiconResolve Include="app.bsky.embed.images" />
		<LexiconResolve Include="app.bsky.embed.external" />
		<LexiconResolve Include="app.bsky.richtext.facet" />
		<LexiconResolve Include="com.atproto.repo.createRecord" />
		<LexiconResolve Include="com.atproto.repo.uploadBlob" />
		<LexiconResolve Include="com.atproto.identity.resolveHandle" />
	</ItemGroup>
</Project>